// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"UR65_SmartPhoneUI","status":true,"description":"スマホ用UI  ver 1.0.0\nUIのサイズをスマートフォン向けに最適化します。","parameters":{"タイトル":"1","メニュー":"1","アイテム":"1","スキル":"1","装備":"1","オプション":"1","ゲーム終了":"1","戦闘":"1","ショップ":"1","イベント関係":"1","アイコン位置修正":"1"}},
{"name":"MPP_SimpleTouch2","status":false,"description":"【ver.2.1】マウスやタッチ操作を変更します。","parameters":{"Cancel Enabled?":"true","Long Press Time":"15","Double Tap Default":"0","Double Tap Name":"ダブルタップ間隔","Double Tap Status":"無効,15,30,45,60","Cursor SE Always?":"false"}},
{"name":"MoreEscapeCodes","status":true,"description":"Extends the number of escape codes in the Show Text command","parameters":{"Face ID Index":"f","Nickname/Handle":"h"}},
{"name":"MPP_MessageEX","status":true,"description":"【ver.1.0】文章表示の機能を拡張したり表示の演出を追加します。","parameters":{"Anime Commons":"","Text Set":"","Text Informations":"0,1,2,3,4,5,6,7,8,9","=== Default Value ===":"","Default Message Row":"4","Default FadeOut Type":"0","Default FadeOut Speed":"5","Default Speed":"60","Default Anime Type":"0","Default Ruby Color":"255,255,255","Default Ruby Size":"14","Default Ruby Outline":"2","Message Name Pos":"0,-56","Default Name Color":"0","Message Name Windowskin":"Window","Message Face Padding":"0,0","Message Face Windowskin":"Window"}},
{"name":"YEP_MessageCore","status":true,"description":"Adds more features to the Message Window to customized the\r\nway your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","Description Wrap":"false","---Font---":"","Font Name":"GameFont","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"6","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 0","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[0]"}},
{"name":"MessageAlignmentEC","status":true,"description":"ver1.03/メッセージのアライメントを変更する制御文字を追加します。","parameters":{"ExtendEC":"at,sp"}},
{"name":"InfoWindow","status":true,"description":"情報表示ウィンドウをメニュー画面に追加するプラグイン","parameters":{}},
{"name":"MPP_ChoiceEX","status":true,"description":"【ver.3.6】選択肢の機能拡張","parameters":{"maxPageRow":"6","=== Command ===":"","Plugin Commands":"{\"ChoicePos\":\"ChoicePos\",\"ChoiceVariableId\":\"ChoiceVariableId\",\"ChoiceRect\":\"ChoiceRect\"}","Event Comment":"{\"ChoiceHelp\":\"選択肢ヘルプ\"}"}},
{"name":"MPP_CharaGraphics","status":true,"description":"【ver.1.0】イベントの画像をキャラクターと同じにします。","parameters":{}},
{"name":"Torigoya_InputNamePrompt","status":true,"description":"Input name with prompt","parameters":{"Max Length":"7","Message":"名前を入力してください","Maximum Message":"(%1 characters or less)"}},
{"name":"MapNameExtend","status":true,"description":"MapNameWindowExtendPlugin","parameters":{"PositionX":"","PositionY":"100","MoveXInFade":"","MoveYInFace":"","AllDuration":"","FadeInSpeed":"","Width":"","ShowWindow":"OFF","BackgroundImage":"","ShowRealName":"OFF","UseControlCharacter":"OFF"}},
{"name":"Torigoya_InputNicknamePrompt","status":true,"description":"Input name with prompt","parameters":{"Max Length":"9","Message":"呼び方を入力してください。","Maximum Message":"(%1 characters or less)"}},
{"name":"ParallelPreload","status":false,"description":"並列プリロードプラグイン","parameters":{"素材一覧データ":"MV_Project","ロード間隔":"0","ログ出力":"OFF"}},
{"name":"FacePicture","status":true,"description":"FacePicturePlugin","parameters":{}},
{"name":"PicturePriorityCustomize","status":true,"description":"PicturePriorityCustomizePlugin","parameters":{"UpperPictureId":"10","LowerPictureId":"0","LowerPictureZ":"2"}},
{"name":"LoopTagChecker","status":false,"description":"bgmとbgsの音楽ファイルにループタグがついているかチェックします。","parameters":{"folder":"both","display":"both"}},
{"name":"EventDebugger","status":false,"description":"EventDebuggerPlugin","parameters":{"StepStart":"F7","StepIn":"F11","StepOver":"F10","Continue":"F6","ToggleWindow":"F12","WatchVariable":"F1","MaxWatchNum":"3","EventTest":"true","SuppressFunc":"false","OkHandler":"F11","CancelHandler":"F6","ScriptDebug":"1","DisableDebugCtrlKey":"true"}}
];
